
export const CustomerActionTypes = {
  GET_ALL_CUSTOMERS: 'GET_ALL_CUSTOMERS',
  GET_ALL_CUSTOMERS_START: 'GET_ALL_CUSTOMERS_START',
  GET_ALL_CUSTOMERS_SUCCESS: 'GET_ALL_CUSTOMERS_SUCCESS',
  GET_ALL_CUSTOMERS_ERROR: 'GET_ALL_CUSTOMERS_ERROR',
};
